name: "Bitcoin PV Mining"
version: "1.0.29"
slug: bitcoin_pv_mining
description: "Dynamische Steuerung von Bitcoin-Mining und Energiekomponenten basierend auf PV-Überschuss"
startup: application
boot: auto
ingress: true
ingress_port: 8050
panel_icon: "mdi:chart-sankey"
panel_title: "PV-Mining"
#ports:
#  "8050/tcp": 8050
homeassistant_api: true
icon: "icon.png"
arch:
  - amd64

build:
  dockerfile: Dockerfile

category: automation

options:
  miner_1_power_kw: 3.5
  miner_2_power_kw: 3.7
  miner_3_power_kw: 5.5
  miner_4_power_kw: 5.5
  electricity_price_eur_kwh: 0.30

schema:
  miner_1_power_kw: float
  miner_2_power_kw: float
  miner_3_power_kw: float
  miner_4_power_kw: float
  electricity_price_eur_kwh: float

