name: "Bitcoin PV Mining"
version: "2.0.43"
slug: "bitcoin_pv_mining"
description: "PV-basierte Bitcoin Mining Steuerung mit Web-UI"
ingress: true
ingress_port: 21000
panel_icon: "mdi:currency-btc"
panel_title: "Bitcoin PV"
startup: services
init: false
homeassistant_api: false
arch:
  - amd64
  - aarch64
  - armv7