name: "Bitcoin PV Mining"
version: "2.1.42"
slug: "bitcoin_pv_mining"
description: "PV-based Bitcoin mining control with web UI"
ingress: true
ingress_port: 21000
panel_icon: "mdi:currency-btc"
panel_title: "Bitcoin PV"
startup: services
init: false
homeassistant_api: true
map:
  - config:rw
arch:
  - amd64
  - aarch64
  - armv7

icon: "icon.png"
