name: "Bitcoin PV Mining"
version: "2.0.9"
slug: "bitcoin_pv_mining"
description: "PV-basierte Bitcoin Mining Steuerung mit Web-UI"
startup: services
ingress: true
ingress_port: 21000
panel_icon: mdi:currency-btc
panel_title: Bitcoin PV
init: false
homeassistant_api: true
map:
  - config:rw
arch:
  - amd64
  - aarch64
  - armv7
ports:
  21000/tcp: null
