name: "Bitcoin PV-mining"
version: "0.4.60"
slug: "bitcoin_pv_mining"
description: "PV-based Bitcoin mining control with web UI"
ingress: true
ingress_port: 21000
panel_icon: "mdi:currency-btc"
panel_title: "Bitcoin PV-mining"
startup: services
init: false
homeassistant_api: true
map:
  - config:rw
arch:
  - amd64
  - aarch64
  - armv7

icon: "icon.png"

git_source:
  base_url: "https://github.com"
  project_path: "BitcoinSolutionGit/PV_Mining_HA"
  branch: "main"
  yamls_dir: "yamls"
  token_env: "GITLAB_TOKEN"

  # input_boolean.bitcoin_miner1_toggle switchen zum einschalten
  # oder direkt das script: bitcoin_miner1_ein:
  #                         alias: Bitcoin Miner1 Ein
  # input_boolean.bitcoin_miner_toggle end of switch on or off

  # https://github.com/sponsors/BitcoinSolutionGit

  # https://github.com/BitcoinSolutionGit/PV_Mining_HA

