name: Bitcoin PV Mining
version: "1.0.0"
slug: bitcoin_pv_mining
description: "Dynamische Steuerung von Bitcoin-Mining und Energiekomponenten basierend auf PV-Überschuss"
startup: application
boot: auto
homeassistant_api: true
options:
  miner_1_power_kw: 3.5
  miner_2_power_kw: 3.7
  miner_3_power_kw: 5.5
  miner_4_power_kw: 5.5
  electricity_price_eur_kwh: 0.30
schema:
  miner_1_power_kw: float
  miner_2_power_kw: float
  miner_3_power_kw: float
  miner_4_power_kw: float
  electricity_price_eur_kwh: float
