name: "Bitcoin PV-mining"
version: "0.6.38"
slug: "bitcoin_pv_mining"
description: "PV-based Bitcoin mining control with web UI"
ingress: true
ingress_port: 21000
panel_icon: "mdi:currency-btc"
panel_title: "Bitcoin PV-mining"
startup: services
init: false
homeassistant_api: true
map:
  - config:rw
arch:
  - amd64
  - aarch64
  - armv7

icon: "icon.png"

git_source:
  base_url: "https://github.com"
  project_path: "BitcoinSolutionGit/PV_Mining_HA"
  branch: "main"
  yamls_dir: "yamls"
  token_env: "GITLAB_TOKEN"

environment:
  ENABLE_MOBILE_POLLING: "1"

pv_mining_addon:
  ui:
    background_color: "#B0CCF7"    # dein dunkleres Grau

  # input_boolean.bitcoin_miner1_toggle switchen zum einschalten
  # oder direkt das script: bitcoin_miner1_ein:
  #                         alias: Bitcoin Miner1 Ein
  # input_boolean.bitcoin_miner_toggle end of switch on or off

  # https://github.com/sponsors/BitcoinSolutionGit
  # https://github.com/BitcoinSolutionGit/PV_Mining_HA
  # https://license.bitcoinsolution.at/var/pending/get.php?install_id=TEST

  #2B2F36 – sattes Slate-Grau (mein Favorit)
  #23272E – GitHub-Dark-mäßig, etwas kühler
  #2E3440 – Nord-Theme “Polar Night”
  #1F2329 – sehr dunkel, fast schwarz
  #30343A – neutral, minimal heller
  #2B2D31 – Discord-Dark Richtung