name: "Bitcoin PV Mining"
version: "2.0.7"
slug: "bitcoin_pv_mining"
description: "PV-basierte Bitcoin Mining Steuerung mit Web-UI"
ingress: true
ingress_port: 8080
panel_icon: "mdi:currency-btc"
panel_title: "PV Mining"
startup: services
init: false
homeassistant_api: false
arch:
  - amd64
  - aarch64
  - armv7

