heater:
  mapping:
    input_warmwasser_cache:
    input_heizstab_cache:
  variables:
    max_power_heater:
    wanted_water_temperature: 60
    power_unit: kW
    heat_unit: "°C"
    manual_override: false
    manual_override_percent: 0