heater:
  mapping:
    input_warmwasser_cache:
    input_heizstab_cache:
  variables:
    max_power_heater:
    wanted_water_temperature: 60
    power_unit: kW
    heat_unit: "°C"
    manual_override: false
    manual_override_percent: 0
    zero_export_kick_enabled: true      # <— einschalten
    zero_export_kick_kw: 0.2            # 200 W „Anfahr-Impuls“
    zero_export_kick_cooldown_s: 60     # min. Abstand zwischen Kicks