feature_flags:
  miners_active: true
  heater_active: true
  wallbox_active: true
  battery_active: true
  show_dev_tab: false
  show_battery_tab: false
  show_wallbox_tab: false

ui_price_thresholds:
  market:
    green_eur_kwh: 0.10
    yellow_eur_kwh: 0.20
  blended:
    green_eur_kwh: 0.10
    yellow_eur_kwh: 0.20

docs:
  readme_de_url: "https://github.com/BitcoinSolutionGit/PV_Mining_HA/blob/master/Readme_DE.md"
  readme_en_url: "https://github.com/BitcoinSolutionGit/PV_Mining_HA/blob/master/Readme_EN.md"

# Globaler Default (gilt für alle diskreten Verbraucher, falls kein Override):
discrete_on_fraction: 0.10   # = 10 %

# Feiner je Consumer:
cooling:
  on_fraction: 0.10

miner:
  on_fraction: 0.10