feature_flags:
  miners_active: true
  heater_active: true
  wallbox_active: true
  battery_active: true
  show_dev_tab: false
  show_battery_tab: false
  show_wallbox_tab: false

ui_price_thresholds:
  market:
    green_eur_kwh: 0.10
    yellow_eur_kwh: 0.20
  blended:
    green_eur_kwh: 0.10
    yellow_eur_kwh: 0.20

docs:
  readme_de_url: "https://github.com/BitcoinSolutionGit/PV_Mining_HA/blob/master/Readme_DE.md"
  readme_en_url: "https://github.com/BitcoinSolutionGit/PV_Mining_HA/blob/master/Readme_EN.md"

ui:
  background_color: "#1F2329"   # sanftes Hellgrau; ändere frei

  #2B2F36 – sattes Slate-Grau (mein Favorit)

  #23272E – GitHub-Dark-mäßig, etwas kühler

  #2E3440 – Nord-Theme “Polar Night”

  #1F2329 – sehr dunkel, fast schwarz

  #30343A – neutral, minimal heller

  #2B2D31 – Discord-Dark Richtung