settings:
  # PV-Kosten-Modell:
  #  - zero   => PV = 0 €/kWh (bisher)
  #  - feedin => PV = Einspeisetarif - network_fee_up (nicht negativ)
  pv_cost_policy: zero

  # Falls 'feedin':
  feedin_price_mode: fixed     # fixed | sensor
  feedin_price_value: 0.10     # €/kWh  (wenn fixed)
  feedin_price_sensor: ""      # z.B. sensor.einspeisetarif

  # BTC-Ökonomie (ein Teil existiert ggf. schon)
  block_reward_btc: 3.125
  sell_tax_percent: 27.5
  btc_price_currency: USD
  fx_usd_to_eur: 0.93

  cooling_feature_enabled: false

  surplus_guard_w: 150.0   # z. B. 100–300 W
  surplus_guard_pct: 0.00  # optionaler prozentualer Guard (0–0.05)
